# Generated by Django 3.0.6 on 2020-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
